### ISSUE TITLE
Language!?

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/fikspunktsregister#7]
@kbevers and @busstoptaktik 

What is the language of the API? The python code you sent us initially was all in danish. `hent_punkter`etc.

I think we should at least try to be consistent, so the chosen language applies to everything (modules, classes, methods, docstrings, other documentation etc).

At the moment there are some danlish in the db schema. I am thinking of "event". Like this there are probably situations where the english word is going to be more appropriate. For example for some programming terms. `API` would be one of those.

**Comment by busstoptaktik** [comment]
The DB table- and field names are mostly in Danish (because... corporate policy).

Geodesy, however, is international, and our primary computational tool, GNU Gama speaks English, så for at stoppe det bilinguale vanvid as soon as possible, we (that is: @kbevers && @busstoptaktik ) believe making the API as anglo-american as overhovedet muligt would be preferable.

Personally, I prefer the flavo**u**r of British English to the flavor of American English, although in an API we can probably work around the use of Benjamin Franklin's linguistic rationalizations?

**Comment by AsgerPetersen** [comment]
I think we may need help translating object types and properties from the data model. I have just implemented with the same naming as in the database.

I suggest that I leave it like that for now, and then we will have to do a translation at some point when the schema is not moving as much as it does now.
